apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: python-helloworld-jordan
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: docker.io/justeh/python-helloworld-jordan
        env:
        - name: TARGET
          value: "Python Sample v1"